### PR TITLE
Implement 2020 updates to Kyouiku ordering

### PR DESCRIPTION
**Pull request by suushiemaniac**
The Japanese ministry of education has updated the list of Kyouiku Kanji in 2017, and the changes jsut came into effect as of January 2020.

The gist of the updates is to teach 20 additional Kanji used in prefecture names (熊、阜、潟、岡 etc) in primary school already (until now these used to be part of the middle school syllabus). Other Kanji from Year 4 have been moved to other school years to keep the overall list balanced.

The Kyouiku Kanji now officially amount to 1026 characters. An official document detailing the updates can be found [directly at MEXT](https://www.mext.go.jp/component/a_menu/education/micro_detail/__icsFiles/afieldfile/2019/03/18/1387017_002.pdf) (details on page 18)
A compact list of updates can also be found at the Japanese [Wikipedia article page](https://ja.wikipedia.org/wiki/%E5%AD%A6%E5%B9%B4%E5%88%A5%E6%BC%A2%E5%AD%97%E9%85%8D%E5%BD%93%E8%A1%A8#%E6%94%B9%E5%AE%9A%E5%89%8D%E3%81%A8%E3%81%AE%E6%AF%94%E8%BC%83) listing all Kyouiku kanji.

The following SQL queries were used to update the SQLite DB:
```sql
UPDATE edict SET grade = 'Primary school' WHERE kanji IN ('茨','媛','岡','潟','岐','熊','香','佐','埼','崎','滋','鹿','縄','井','沖','栃','奈','梨','阪','阜');

UPDATE kanjidict SET grade = 'Kyōiku-Jōyō (4th grade of primary school)' WHERE kanji IN ('賀','群','徳','富','城','茨','媛','岡','潟','岐','熊','香','佐','埼','崎','滋','鹿','縄','井','沖','栃','奈','梨','阪','阜');
UPDATE kanjidict SET grade = 'Kyōiku-Jōyō (5th grade of primary school)' WHERE kanji IN ('囲','紀','喜','救','型','航','告','殺','士','史','象','賞','貯','停','堂','得','毒','費','粉','脈','歴');
UPDATE kanjidict SET grade = 'Kyōiku-Jōyō (6th grade of primary school)' WHERE kanji IN ('胃','腸','恩','券','承','舌','銭','退','敵','俵','預');
```

A sanity check can be performed by counting the respective entries in the `kanjidict` table:
```sql
SELECT COUNT(*) FROM kanjidict WHERE grade LIKE 'Kyōiku-Jōyō%';
SELECT COUNT(*) FROM kanjidict WHERE grade LIKE 'Jōyō%';
```

These queries yield results `1026` and `1110` respectively, resulting in a (correct!) total of `2136` Jouyou kanji.

### CODE REVIEW

**Comment by mifunetoshiro** [comment]
Thank you.

**Comment by mifunetoshiro** [comment]
@suushiemaniac Could I ask another favour? I don't have git installed, and I can't upload a file larger than 25MB via the web browser to GitHub; could you by chance download kanjidb.sqlite from here https://www.mediafire.com/file/skp8wlhgbpqyddk/kanjidb.sqlite/file with the changes from https://github.com/mifunetoshiro/kanjium/commit/782a26270a04241574bcae102fdd33ae6511da36 and issue another pull request so I can merge it? Thanks

**Comment by suushiemaniac** [comment]
Yup, sure! I'm sorry I was totally unaware that there are source files to keep in sync with the DB. Otherwise I'd have included them in my PR…

**Comment by suushiemaniac** [comment]
There you go: https://github.com/mifunetoshiro/kanjium/pull/12

**Comment by mifunetoshiro** [comment]
Thanks again!

**Pull request merged**
